version: '3.9'
services:
  database:
    container_name: greengame
    image: mariadb:11.0.2
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"